name: hello

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Check Docker version
        run: |
          echo "Docker Version:"
          docker --version
          echo "Docker Detailed Info:"
          docker version

      - name: Check Python version
        run: |
          echo "Python Version:"
          python --version || python3 --version
          echo "Python Detailed Version:"
          python3 -V

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
